compute_environment: LOCAL_MACHINE
debug: false
deepspeed_config:
  gradient_accumulation_steps: 16
  gradient_clipping: 1.0
  offload_optimizer_device: cpu
  offload_param_device: cpu
  zero3_init_flag: true
  zero_stage: 3
  zero_optimization:
    stage: 3
    offload_optimizer:
      device: cpu
      pin_memory: true
    offload_param:
      device: cpu
      pin_memory: true
    overlap_comm: true
    contiguous_gradients: true
    reduce_bucket_size: auto
    stage3_prefetch_bucket_size: auto
    stage3_param_persistence_threshold: auto
    sub_group_size: auto
    stage3_max_live_parameters: auto
    stage3_max_reuse_distance: auto
    stage3_gather_16bit_weights_on_model_save: true
  bf16:
    enabled: true
  optimizer:
    type: AdamW
    params:
      lr: 5e-7
      betas: [0.9, 0.999]
      eps: 1e-8
      weight_decay: 0.01
  scheduler:
    type: WarmupLR
    params:
      warmup_min_lr: 0
      warmup_max_lr: 5e-7
      warmup_num_steps: 50
  steps_per_print: 2
  train_batch_size: auto
  train_micro_batch_size_per_gpu: auto
  wall_clock_breakdown: false
distributed_type: DEEPSPEED
downcast_bf16: 'yes'
machine_rank: 0
main_training_function: main
mixed_precision: 'bf16'
num_machines: 1
num_processes: 2
rdzv_backend: static
same_network: true
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: true