train_batch_size: 2
train_micro_batch_size_per_gpu: 1
gradient_accumulation_steps: 4
optimizer:
  type: Adam
  params:
    lr: 1e-5
    betas: [0.9, 0.999]
    eps: 1e-8
    weight_decay: 1e-1
bf16:
  enabled: true
zero_optimization:
  stage: 3
  offload_optimizer:
    device: cpu
    pin_memory: true
  offload_param:
    device: cpu
    pin_memory: true
